version: '3.8'
#Mongo volumes currently do not work on windows.
services:
  rasatalk:
    build:
      context: .
      dockerfile: ./internals/docker/Dockerfile
    command: npm run start:prod
    environment:
      - MONGOCONNECTIONSTRING=mongodb://mongodb:27017/admin
      - RASASERVER=http://rasa:5000
      - DEBUG=*,-babel
      - PORT=80
    ports:
      - "8080:80"
    volumes:
      - ./app:/code/app
      - ./package.json:/code/package.json
      - ./yarn.lock:/code/yarn.lock
      - ./server:/code/server
    links:
      - "rasa"
      - "mongodb"

  rasa:
    container_name: "rasa"
    image: rasa/rasa_nlu:stable-full
    restart: always
    volumes:
      - ./data/rasa/projects:/app/projects
      - ./data/rasa/logs:/app/logs
      - ./data/rasa/data:/app/data

  mongodb:
    container_name: "mongo"
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    #volumes:
      #- ./data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=your_username
      - MONGO_INITDB_ROOT_PASSWORD=your_password